const USER="admin", PASS="Eyakub@12345";let products=JSON.parse(localStorage.getItem("eyakub_products")||"null")||window.EYAKUB_PRODUCTS||[];let orders=JSON.parse(localStorage.getItem("eyakub_orders")||"[]");const $=s=>document.querySelector(s);const $$=s=>document.querySelectorAll(s);function save(){localStorage.setItem("eyakub_products",JSON.stringify(products))}
function login(){if($("#user").value===USER&&$("#pass").value===PASS){sessionStorage.setItem("eyakub_admin","1");$("#login").classList.add("hidden");$("#panel").classList.remove("hidden");dashboard()}else alert("Username বা password ভুল।")}
$("#loginForm").onsubmit=e=>{e.preventDefault();login()};if(sessionStorage.getItem("eyakub_admin")==="1"){$("#login").classList.add("hidden");$("#panel").classList.remove("hidden")}
$("#logout").onclick=()=>{sessionStorage.removeItem("eyakub_admin");location.reload()};$("#sideBtn").onclick=()=>$("#panel aside").classList.toggle("open");
$$("[data-view]").forEach(b=>b.onclick=()=>{let v=b.dataset.view;if(v==="dashboard")dashboard();if(v==="products")productView();if(v==="orders")orderView();if(v==="settings")settingsView()});
function dashboard(){$("#viewTitle").textContent="Dashboard";$("#view").innerHTML=`<div class="stats"><div class="stat">মোট পণ্য<b>${products.length}</b><small>জুতা ${products.filter(p=>p.category==="shoes").length} • ব্যাগ ${products.filter(p=>p.category==="bags").length}</small></div><div class="stat">স্টক<b>${products.reduce((a,p)=>a+p.stock,0)}</b><small>সব পণ্যের মোট quantity</small></div><div class="stat">Orders<b>${orders.length}</b><small>এই ব্রাউজারে সংরক্ষিত</small></div><div class="stat">Low Stock<b>${products.filter(p=>p.stock<10).length}</b><small>১০ পিসের কম</small></div></div><div class="table-wrap"><div style="padding:16px"><h3>সাম্প্রতিক অর্ডার</h3>${orders.slice(0,5).map(orderCard).join("")||"<p>এখনও কোনো order নেই।</p>"}</div></div>`}
function productView(){ $("#viewTitle").textContent="Products";$("#view").innerHTML=`<div class="toolbar"><input id="pSearch" placeholder="পণ্য খুঁজুন..."><button class="add" id="addProduct">+ নতুন পণ্য</button></div><div class="table-wrap"><table class="table"><thead><tr><th>ছবি</th><th>পণ্য</th><th>Category</th><th>Price</th><th>Stock</th><th>SKU</th><th>Action</th></tr></thead><tbody id="tbody"></tbody></table></div>`;renderRows();$("#addProduct").onclick=()=>openEditor();$("#pSearch").oninput=renderRows}
function renderRows(){let q=($("#pSearch")?.value||"").toLowerCase();$("#tbody").innerHTML=products.filter(p=>(p.name+" "+p.sku).toLowerCase().includes(q)).map(p=>`<tr><td><img class="thumb" src="${p.image}"></td><td><b>${p.name}</b></td><td>${p.category}</td><td>৳${p.price.toLocaleString()}</td><td>${p.stock}</td><td>${p.sku}</td><td class="act"><button data-edit="${p.id}">Edit</button><button class="danger" data-del="${p.id}">Delete</button></td></tr>`).join("");$$("[data-edit]").forEach(b=>b.onclick=()=>openEditor(b.dataset.edit));$$("[data-del]").forEach(b=>b.onclick=()=>{if(confirm("এই পণ্যটি delete করবেন?")){products=products.filter(p=>p.id!==b.dataset.del);save();renderRows()}})}
function openEditor(id){let p=products.find(x=>x.id===id);$("#editorTitle").textContent=p?"পণ্য Edit":"নতুন পণ্য";$("#productForm").reset();$("#imagePreview").src="";for(let [k,v] of Object.entries(p||{})){let el=$(`[name="${k}"]`);if(el&&el.type!=="file"&&el.type!=="checkbox")el.value=Array.isArray(v)?v.join(", "):v}if(p){$('[name="featured"]').checked=!!p.featured;$('[name="flash"]').checked=!!p.flash;$("#imagePreview").src=p.image}$("#productEditor").classList.add("show")}
$("#closeEditor").onclick=()=>$("#productEditor").classList.remove("show");$('[name="imageFile"]').onchange=e=>{let f=e.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{$("#imagePreview").src=r.result};r.readAsDataURL(f)};
$("#productForm").onsubmit=e=>{e.preventDefault();let fd=new FormData(e.currentTarget),id=fd.get("id")||"PR-"+Date.now();let old=products.find(p=>p.id===id);let file=fd.get("imageFile");let finish=img=>{let p={id,name:fd.get("name"),category:fd.get("category"),sku:fd.get("sku")||id,stock:Number(fd.get("stock")||0),oldPrice:Number(fd.get("oldPrice")||0),price:Number(fd.get("price")||0),colors:fd.get("colors").split(",").map(x=>x.trim()).filter(Boolean),sizes:fd.get("sizes").split(",").map(x=>x.trim()).filter(Boolean),rating:Number(fd.get("rating")||4.5),sold:Number(fd.get("sold")||0),description:fd.get("description")||"",image:img||old?.image||"assets/products/SH-001.svg",featured:fd.get("featured")==="on",flash:fd.get("flash")==="on"};if(old)products=products.map(x=>x.id===id?p:x);else products.unshift(p);save();$("#productEditor").classList.remove("show");productView()};if(file&&file.size){let r=new FileReader();r.onload=()=>finish(r.result);r.readAsDataURL(file)}else finish(fd.get("image"))};
function orderCard(o){let c=o.customer||{};return `<div class="order-card"><div class="order-head"><b>${o.id}</b><span class="status">${o.status||"New"}</span></div><p><b>${c.name||""}</b> • ${c.phone||""}<br>${c.address||""}, ${c.upazila||""}, ${c.district||""}</p><p>${(o.items||[]).map(x=>{let p=products.find(p=>p.id===x.id);return `${p?.name||x.id} × ${x.qty}`}).join("<br>")}</p><b>মোট: ৳${Number(o.total||0).toLocaleString()}</b></div>`}
function orderView(){$("#viewTitle").textContent="Orders";$("#view").innerHTML=`<div class="toolbar"><b>${orders.length}টি order</b><button class="add" id="clearOrders">সব Order মুছুন</button></div>${orders.map(orderCard).join("")||"<div class='settings'>কোনো order নেই।</div>"}`;$("#clearOrders").onclick=()=>{if(confirm("সব order মুছবেন?")){orders=[];localStorage.setItem("eyakub_orders","[]");orderView()}}}
function settingsView(){$("#viewTitle").textContent="Settings";$("#view").innerHTML=`<div class="settings"><h3>স্টোর সেটিংস</h3><p>WhatsApp: <code>966567225245</code></p><p>Facebook: <code>facebook.com/profile.php?id=61594226919156</code></p><hr><h3>গুরুত্বপূর্ণ</h3><p>এই ZIP-এর Admin Panel localStorage-ভিত্তিক। অর্থাৎ GitHub Pages-এ আলাদা customer device থেকে product changes বা orders আপনার admin browser-এ automatically sync হবে না। Customer order WhatsApp-এ পাঠানো হবে। সত্যিকারের multi-device admin + database চালাতে Supabase/Firebase backend যুক্ত করতে হবে।</p><p>Login বদলাতে <code>admin.js</code>-এর USER ও PASS পরিবর্তন করুন।</p></div>`}
if(!sessionStorage.getItem("eyakub_admin")){}else dashboard();