const WA="966567225245", FB="https://www.facebook.com/profile.php?id=61594226919156";
const seed=window.EYAKUB_PRODUCTS||[];
let products=JSON.parse(localStorage.getItem("eyakub_products")||"null")||seed;
let cart=JSON.parse(localStorage.getItem("eyakub_cart")||"[]"), wishlist=JSON.parse(localStorage.getItem("eyakub_wishlist")||"[]");
let activeCat="all", searchTerm="", visible=20, sortMode="popular";
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const money=n=>"৳"+Number(n||0).toLocaleString("en-US");
function save(){localStorage.setItem("eyakub_products",JSON.stringify(products));localStorage.setItem("eyakub_cart",JSON.stringify(cart));localStorage.setItem("eyakub_wishlist",JSON.stringify(wishlist))}
function discount(p){return p.oldPrice>p.price?Math.round((1-p.price/p.oldPrice)*100):0}
function card(p){
 const wished=wishlist.includes(p.id);
 return `<article class="product-card" data-id="${p.id}">
 <div class="product-image"><img src="${p.image}" alt="${p.name}" loading="lazy"><span class="badge">-${discount(p)}%</span><button class="heart" data-wish="${p.id}">${wished?"♥":"♡"}</button></div>
 <div class="product-info"><h3>${p.name}</h3><div><span class="price">${money(p.price)}</span><span class="old">${money(p.oldPrice)}</span></div>
 <div class="meta"><span class="rating">★ ${p.rating}</span> (${p.sold}) • 🔥 ${p.sold>900?"1k+":p.sold} sold</div><button class="buy" data-add="${p.id}">🛒 কার্টে যোগ করুন</button></div></article>`
}
function filtered(){
 let a=products.filter(p=>(activeCat==="all"||p.category===activeCat)&&(!searchTerm||(`${p.name} ${p.sku} ${p.description}`).toLowerCase().includes(searchTerm.toLowerCase())));
 if(sortMode==="low")a.sort((x,y)=>x.price-y.price); if(sortMode==="high")a.sort((x,y)=>y.price-x.price); if(sortMode==="new")a.sort((x,y)=>y.id.localeCompare(x.id));
 else if(sortMode==="popular")a.sort((x,y)=>y.sold-x.sold); return a;
}
function render(){let a=filtered(); $("#productGrid").innerHTML=a.slice(0,visible).map(card).join("")||`<div class="muted">কোনো পণ্য পাওয়া যায়নি।</div>`;
 $("#flashGrid").innerHTML=products.filter(p=>p.flash).slice(0,5).map(card).join(""); $("#popularGrid").innerHTML=products.filter(p=>p.featured).slice(0,6).map(card).join("");
 $("#listingTitle").textContent=searchTerm?`“${searchTerm}” এর ফলাফল`:activeCat==="shoes"?"জুতা সমূহ":activeCat==="bags"?"ব্যাগ সমূহ":"সব পণ্য"; bindCards(); updateCart()}
function bindCards(){$$(".product-card").forEach(c=>c.addEventListener("click",e=>{if(e.target.closest("[data-add]")||e.target.closest("[data-wish]"))return;openProduct(c.dataset.id)}));$$("[data-add]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();addCart(e.currentTarget.dataset.add)}));$$("[data-wish]").forEach(b=>b.addEventListener("click",e=>{e.stopPropagation();toggleWish(e.currentTarget.dataset.wish)}))}
function addCart(id){let p=products.find(x=>x.id===id);if(!p||p.stock<1)return alert("এই পণ্যটি বর্তমানে স্টকে নেই।");let x=cart.find(x=>x.id===id);if(x)x.qty=Math.min(x.qty+1,p.stock);else cart.push({id,qty:1});save();updateCart();$("#cartDrawer").classList.add("show");$("#overlay").classList.add("show")}
function toggleWish(id){wishlist.includes(id)?wishlist=wishlist.filter(x=>x!==id):wishlist.push(id);save();render()}
function updateCart(){let count=cart.reduce((a,x)=>a+x.qty,0),total=cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id)?.price||0)*x.qty,0);$("#cartCount").textContent=count;$("#cartTotal").textContent=money(total);$("#cartItems").innerHTML=cart.length?cart.map(x=>{let p=products.find(p=>p.id===x.id);return `<div class="cart-row"><img src="${p.image}"><div><h4>${p.name}</h4><div class="qty"><button data-dec="${p.id}">−</button><span>${x.qty}</span><button data-inc="${p.id}">+</button></div></div><b>${money(p.price*x.qty)}</b></div>`}).join(""):`<p class="muted">আপনার cart খালি।</p>`;$$("[data-inc]").forEach(b=>b.onclick=()=>changeQty(b.dataset.inc,1));$$("[data-dec]").forEach(b=>b.onclick=()=>changeQty(b.dataset.dec,-1))}
function changeQty(id,d){let x=cart.find(x=>x.id===id),p=products.find(p=>p.id===id);if(!x)return;x.qty+=d;if(x.qty<=0)cart=cart.filter(x=>x.id!==id);if(x.qty>p.stock)x.qty=p.stock;save();updateCart()}
function openProduct(id){let p=products.find(x=>x.id===id);if(!p)return;let related=products.filter(x=>x.category===p.category&&x.id!==p.id).slice(0,4);$("#productDetail").innerHTML=`<div class="detail-image"><img src="${p.image}" alt="${p.name}"></div><div class="detail-info"><div class="muted">${p.sku} • ${p.category==="shoes"?"জুতা":"ব্যাগ"}</div><h2>${p.name}</h2><div class="detail-price">${money(p.price)} <span class="old">${money(p.oldPrice)}</span></div><p>${p.description}</p><p><b>স্টক:</b> ${p.stock} pcs</p><p><b>রেটিং:</b> ⭐ ${p.rating} &nbsp; • &nbsp; ${p.sold} sold</p><p><b>রং:</b></p><div class="chips">${p.colors.map(x=>`<span class="chip">${x}</span>`).join("")}</div><p><b>সাইজ:</b></p><div class="chips">${p.sizes.map(x=>`<span class="chip">${x}</span>`).join("")}</div><br><button class="primary full" data-detail-add="${p.id}">🛒 কার্টে যোগ করুন</button><hr><h3>এই ধরনের আরও পণ্য</h3><div class="chips">${related.map(x=>`<span class="chip" data-related="${x.id}">${x.name}</span>`).join("")}</div></div>`;$("#productModal").classList.add("show");$("[data-detail-add]").onclick=()=>{addCart(id);$("#productModal").classList.remove("show")};$$("[data-related]").forEach(x=>x.onclick=()=>openProduct(x.dataset.related))}
function openCheckout(){if(!cart.length)return alert("আগে cart-এ পণ্য যোগ করুন।");$("#checkoutSummary").innerHTML=cart.map(x=>{let p=products.find(p=>p.id===x.id);return `<div>${p.name} × ${x.qty} — <b>${money(p.price*x.qty)}</b></div>`}).join("")+`<hr><b>মোট: ${money(cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id).price*x.qty),0))}</b>`;$("#checkoutModal").classList.add("show")}
function closeAll(){$("#cartDrawer").classList.remove("show");$("#overlay").classList.remove("show");$$(".modal").forEach(m=>m.classList.remove("show"))}
function cat(c){activeCat=c;visible=20;render();document.querySelector(".products-section").scrollIntoView({behavior:"smooth"})}
$$("[data-cat]").forEach(x=>x.addEventListener("click",()=>cat(x.dataset.cat)));
$("#searchForm").onsubmit=e=>{e.preventDefault();searchTerm=$("#searchInput").value.trim();visible=20;render();document.querySelector(".products-section").scrollIntoView({behavior:"smooth"})};
$("#sort").onchange=e=>{sortMode=e.target.value;render()};$("#loadMore").onclick=()=>{visible+=20;render()};
$("#showAll").onclick=()=>cat("all");$("#showFlash").onclick=()=>{activeCat="all";products.sort((a,b)=>b.flash-a.flash);visible=20;render();document.querySelector(".products-section").scrollIntoView({behavior:"smooth"})};
$("#cartBtn").onclick=()=>{$("#cartDrawer").classList.add("show");$("#overlay").classList.add("show")};$("#overlay").onclick=closeAll;$$(".close,.modal-close").forEach(x=>x.onclick=closeAll);$("#checkoutBtn").onclick=openCheckout;
$("#wishlistBtn").onclick=()=>{if(!wishlist.length)return alert("Wishlist খালি।");searchTerm="";activeCat="all";visible=20;$("#listingTitle").textContent="Wishlist";$("#productGrid").innerHTML=wishlist.map(id=>products.find(p=>p.id===id)).filter(Boolean).map(card).join("");bindCards();document.querySelector(".products-section").scrollIntoView({behavior:"smooth"})};
$("#checkoutForm").onsubmit=e=>{e.preventDefault();let f=new FormData(e.currentTarget), total=cart.reduce((a,x)=>a+(products.find(p=>p.id===x.id).price*x.qty),0);let lines=cart.map(x=>{let p=products.find(p=>p.id===x.id);return `• ${p.name} | Qty: ${x.qty} | ${money(p.price*x.qty)}`}).join("\n");let msg=`*Eyakub Shop - New Order*\n\n${lines}\n\n*Total: ${money(total)}*\n\nনাম: ${f.get("name")}\nফোন: ${f.get("phone")}\nবিকল্প ফোন: ${f.get("altPhone")||"-"}\nবিভাগ: ${f.get("division")}\nজেলা: ${f.get("district")}\nউপজেলা/থানা: ${f.get("upazila")}\nপোস্ট কোড: ${f.get("postal")||"-"}\nঠিকানা: ${f.get("address")}\nপেমেন্ট: ${f.get("payment")}\nনোট: ${f.get("note")||"-"}`;let order={id:"ORD-"+Date.now(),date:new Date().toISOString(),customer:Object.fromEntries(f.entries()),items:cart,total,status:"New"};let orders=JSON.parse(localStorage.getItem("eyakub_orders")||"[]");orders.unshift(order);localStorage.setItem("eyakub_orders",JSON.stringify(orders));window.open(`https://wa.me/${WA}?text=${encodeURIComponent(msg)}`,"_blank");cart=[];save();closeAll();e.currentTarget.reset();render()};
let end=Date.now()+24*60*60*1000;setInterval(()=>{let d=Math.max(0,end-Date.now()),h=Math.floor(d/36e5),m=Math.floor(d/6e4)%60,s=Math.floor(d/1000)%60;$("#timer").textContent=[h,m,s].map(x=>String(x).padStart(2,"0")).join(":")},1000);
$("#mobileMenu").onclick=()=>$("#nav").classList.toggle("mobile-open");
render();